### ISSUE TITLE
Error: Storage root must match that calculated

### ISSUE THREAD

**Issue by akme** [airalab/robonomics#184]
Get the same error on different servers.
Version: 1.1.0-3d61e8c-x86_64-linux-gnu
```
ExecStart=/usr/local/bin/robonomics --name <name> --validator --lighthouse-account <account> --parachain-id 2077 --execution Wasm -- --execution Wasm
```
```
Aug 25 08:35:18 ns3126014 robonomics[3024152]: 2021-08-25 08:35:18 [Parachain] 💤 Idle (25 peers), best: #104982 (0x0f05…9054), finalized #104965 (0x737a…bd0a), ⬇ 91.1kiB/s ⬆ 4.0kiB/s
Aug 25 08:35:18 ns3126014 robonomics[3024152]: 2021-08-25 08:35:18 [Relaychain] ✨ Imported #409074 (0x7916…e1f5)
Aug 25 08:35:18 ns3126014 robonomics[3024152]: 2021-08-25 08:35:18 [Relaychain] ♻️  Reorg on #409074,0x7916…e1f5 to #409074,0xeaf0…2b79, common ancestor #409073,0x4375…dd3d
Aug 25 08:35:18 ns3126014 robonomics[3024152]: 2021-08-25 08:35:18 [Relaychain] ✨ Imported #409074 (0xeaf0…2b79)
Aug 25 08:35:18 ns3126014 robonomics[3024152]: 2021-08-25 08:35:18 [Relaychain] ✨ Imported #409074 (0xfa5e…068a)
Aug 25 08:35:18 ns3126014 robonomics[3024152]: 2021-08-25 08:35:18 [Relaychain] 💤 Idle (40 peers), best: #409074 (0xeaf0…2b79), finalized #408919 (0x2430…0641), ⬇ 118.7kiB/s ⬆ 28.3kiB/s
Aug 25 08:35:19 ns3126014 robonomics[3024152]: 2021-08-25 08:35:19 [Parachain] panicked at 'Storage root must match that calculated.', /home/akru/.cargo/git/checkouts/substrate-7e08433d4c370a21/74101dc/frame/executive/src/lib.rs:469:9
Aug 25 08:35:19 ns3126014 robonomics[3024152]: 2021-08-25 08:35:19 [Parachain] Block prepare storage changes error:
Aug 25 08:35:19 ns3126014 robonomics[3024152]: RuntimeApiError(Application(Execution(Other("Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n    0: 0x1c09 - <unknown>!rust_begin_unwind\n    1: 0x1956 - <unknown>!core::panicking::panic_fmt::h0dfe153eb0ef456a\n    2: 0x102f - <unknown>!core::panicking::panic::ha2f229d777a180c9\n    3: 0x31cec - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block::hf7d25b4c1487961a\n    4: 0xa2ac9 - <unknown>!Core_execute_block\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\n"))))
Aug 25 08:35:19 ns3126014 robonomics[3024152]: 2021-08-25 08:35:19 [Parachain] 💔 Error importing block 0x796241dc833de5ce85a20d63dcdfe38b118332cefbd968ea18700ab64fe65023: Err(Other(ClientImport("Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: wasm trap: unreachable\\nwasm backtrace:\\n    0: 0x1c09 - <unknown>!rust_begin_unwind\\n    1: 0x1956 - <unknown>!core::panicking::panic_fmt::h0dfe153eb0ef456a\\n    2: 0x102f - <unknown>!core::panicking::panic::ha2f229d777a180c9\\n    3: 0x31cec - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block::hf7d25b4c1487961a\\n    4: 0xa2ac9 - <unknown>!Core_execute_block\\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\\n\")")))
Aug 25 08:35:19 ns3126014 robonomics[3024152]: 2021-08-25 08:35:19 [Parachain] panicked at 'Storage root must match that calculated.', /home/akru/.cargo/git/checkouts/substrate-7e08433d4c370a21/74101dc/frame/executive/src/lib.rs:469:9
Aug 25 08:35:19 ns3126014 robonomics[3024152]: 2021-08-25 08:35:19 [Parachain] Block prepare storage changes error:
Aug 25 08:35:19 ns3126014 robonomics[3024152]: RuntimeApiError(Application(Execution(Other("Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n    0: 0x1c09 - <unknown>!rust_begin_unwind\n    1: 0x1956 - <unknown>!core::panicking::panic_fmt::h0dfe153eb0ef456a\n    2: 0x102f - <unknown>!core::panicking::panic::ha2f229d777a180c9\n    3: 0x31cec - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block::hf7d25b4c1487961a\n    4: 0xa2ac9 - <unknown>!Core_execute_block\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\n"))))
Aug 25 08:35:19 ns3126014 robonomics[3024152]: 2021-08-25 08:35:19 [Parachain] 💔 Error importing block 0x796241dc833de5ce85a20d63dcdfe38b118332cefbd968ea18700ab64fe65023: Err(Other(ClientImport("Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: wasm trap: unreachable\\nwasm backtrace:\\n    0: 0x1c09 - <unknown>!rust_begin_unwind\\n    1: 0x1956 - <unknown>!core::panicking::panic_fmt::h0dfe153eb0ef456a\\n    2: 0x102f - <unknown>!core::panicking::panic::ha2f229d777a180c9\\n    3: 0x31cec - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block::hf7d25b4c1487961a\\n    4: 0xa2ac9 - <unknown>!Core_execute_block\\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\\n\")")))
Aug 25 08:35:21 ns3126014 robonomics[3024152]: 2021-08-25 08:35:21 [Parachain] panicked at 'Storage root must match that calculated.', /home/akru/.cargo/git/checkouts/substrate-7e08433d4c370a21/74101dc/frame/executive/src/lib.rs:469:9
Aug 25 08:35:21 ns3126014 robonomics[3024152]: 2021-08-25 08:35:21 [Parachain] Block prepare storage changes error:
Aug 25 08:35:21 ns3126014 robonomics[3024152]: RuntimeApiError(Application(Execution(Other("Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n    0: 0x1c09 - <unknown>!rust_begin_unwind\n    1: 0x1956 - <unknown>!core::panicking::panic_fmt::h0dfe153eb0ef456a\n    2: 0x102f - <unknown>!core::panicking::panic::ha2f229d777a180c9\n    3: 0x31cec - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block::hf7d25b4c1487961a\n    4: 0xa2ac9 - <unknown>!Core_execute_block\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\n"))))
Aug 25 08:35:21 ns3126014 robonomics[3024152]: 2021-08-25 08:35:21 [Parachain] 💔 Error importing block 0x796241dc833de5ce85a20d63dcdfe38b118332cefbd968ea18700ab64fe65023: Err(Other(ClientImport("Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: wasm trap: unreachable\\nwasm backtrace:\\n    0: 0x1c09 - <unknown>!rust_begin_unwind\\n    1: 0x1956 - <unknown>!core::panicking::panic_fmt::h0dfe153eb0ef456a\\n    2: 0x102f - <unknown>!core::panicking::panic::ha2f229d777a180c9\\n    3: 0x31cec - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block::hf7d25b4c1487961a\\n    4: 0xa2ac9 - <unknown>!Core_execute_block\\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\\n\")")))
Aug 25 08:35:21 ns3126014 robonomics[3024152]: 2021-08-25 08:35:21 [Parachain] panicked at 'Storage root must match that calculated.', /home/akru/.cargo/git/checkouts/substrate-7e08433d4c370a21/74101dc/frame/executive/src/lib.rs:469:9
Aug 25 08:35:21 ns3126014 robonomics[3024152]: 2021-08-25 08:35:21 [Parachain] Block prepare storage changes error:
Aug 25 08:35:21 ns3126014 robonomics[3024152]: RuntimeApiError(Application(Execution(Other("Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n    0: 0x1c09 - <unknown>!rust_begin_unwind\n    1: 0x1956 - <unknown>!core::panicking::panic_fmt::h0dfe153eb0ef456a\n    2: 0x102f - <unknown>!core::panicking::panic::ha2f229d777a180c9\n    3: 0x31cec - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block::hf7d25b4c1487961a\n    4: 0xa2ac9 - <unknown>!Core_execute_block\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\n"))))
Aug 25 08:35:21 ns3126014 robonomics[3024152]: 2021-08-25 08:35:21 [Parachain] 💔 Error importing block 0x796241dc833de5ce85a20d63dcdfe38b118332cefbd968ea18700ab64fe65023: Err(Other(ClientImport("Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: wasm trap: unreachable\\nwasm backtrace:\\n    0: 0x1c09 - <unknown>!rust_begin_unwind\\n    1: 0x1956 - <unknown>!core::panicking::panic_fmt::h0dfe153eb0ef456a\\n    2: 0x102f - <unknown>!core::panicking::panic::ha2f229d777a180c9\\n    3: 0x31cec - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block::hf7d25b4c1487961a\\n    4: 0xa2ac9 - <unknown>!Core_execute_block\\nnote: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information\\n\")")))
```

**Comment by akru** [comment]
Is your node sync stoped? As result of errors above?

**Comment by akme** [comment]
It continues to sync, but the collation process stops.

**Comment by akru** [comment]
That looks weird, what’s about node restart? Probably someone of your neighbors share bad block.

**Comment by akme** [comment]
It's two different nodes in two different data centers. After node restart, it shows lots of:
```
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Applying authority set change scheduled at block #411482
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Applying GRANDPA set change to new set with 18 authorities
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Imported justification for block #411482 that triggers command Changing authorities, signaling voter.
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Applying authority set change scheduled at block #411490
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Applying GRANDPA set change to new set with 18 authorities
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Imported justification for block #411490 that triggers command Changing authorities, signaling voter.
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Applying authority set change scheduled at block #411499
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Applying GRANDPA set change to new set with 18 authorities
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Imported justification for block #411499 that triggers command Changing authorities, signaling voter.
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Applying authority set change scheduled at block #411507
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Applying GRANDPA set change to new set with 18 authorities
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Imported justification for block #411507 that triggers command Changing authorities, signaling voter.
Aug 25 14:06:14 ns3126014 robonomics[3104325]: 2021-08-25 14:06:14 [Relaychain] 👴 Applying authority set change scheduled at block #411517
```

**Comment by akru** [comment]
That’s not a problem, your relay chain looks not synced

**Comment by akru** [comment]
Hi, yes, it's known bug. Current solution is disable cache by `--state-cache-size=1`.
