### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.'

### ISSUE THREAD

**Issue by base1217** [airalab/robonomics#237]
Client version: 1.6.2
Role: Non-collating node
ParaId: 2048

Node doesn't crash it affects on networks responsibilities in mostly. 
![image](https://user-images.githubusercontent.com/41649731/150431449-f8d999fc-d01e-4067-af95-5fb73c18fe37.png)
![image](https://user-images.githubusercontent.com/41649731/150432169-14750665-f714-4add-9f88-70652fa6f0f4.png)

```
====================

Version: 1.6.2-7937f3d5-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:500:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:498:5
   5: core::panicking::panic_fmt
             at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:107:14
   6: <main_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,main_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<main_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<main_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<main_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<main_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<main_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<main_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<main_runtime::Runtime>)>>>>::execute_block
   7: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
   8: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
   9: <main_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_execute_block_runtime_api_impl
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  16: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  17: tokio::runtime::task::raw::poll
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
  20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/alloc/src/boxed.rs:1694:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/alloc/src/boxed.rs:1694:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/sys/unix/thread.rs:106:17
  21: start_thread
  22: clone


Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/d36550a/frame/executive/src/lib.rs:488

This is a bug. Please report it at:

	https://github.com/airalab/robonomics/issues/new

2022-01-20 22:12:30 [Parachain] panicked at 'Storage root must match that calculated.', /cargo-home/git/checkouts/substrate-7e08433d4c370a21/d36550a/frame/executive/src/lib.rs:488:9    
2022-01-20 22:12:30 [Parachain] Block prepare storage changes error:
RuntimeApiError(Application(Execution(Other("Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n    0: 0x203c - <unknown>!rust_begin_unwind\n    1: 0x1caf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349\n    2: 0x74f1b - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hf5feea85a388513e\n    3: 0x16eff0 - <unknown>!Core_execute_block\n"))))    
2022-01-20 22:12:30 [Parachain] 💔 Error importing block 0xec0ee7708ecabd76dd989b640ae28e83d9a8fcf40f1cd5280b811f358d380690: Err(Other(ClientImport("Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: wasm trap: unreachable\\nwasm backtrace:\\n    0: 0x203c - <unknown>!rust_begin_unwind\\n    1: 0x1caf - <unknown>!core::panicking::panic_fmt::h6314b5c91abe7349\\n    2: 0x74f1b - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hf5feea85a388513e\\n    3: 0x16eff0 - <unknown>!Core_execute_block\\n\")")))    
```

**Comment by cybers4pien** [comment]
Try to run it with `--state-cache-size=0`

> Note that you need use --state-cache-size=0 in the collator's service launch. This parameter is important for the stability of the collator. You can see more info in the related issue on github.
https://wiki.robonomics.network/docs/en/how-to-launch-the-robonomics-collator/

#234
